#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

cp -r 0.org 0
runApplication blockMesh

runApplication setSet -batch baffle.setSet

unset FOAM_SETNAN
unset FOAM_SIGFPE

# Add the patches for the baffles
runApplication changeDictionary -literalRE
rm log.changeDictionary

# Create first baffle
createBaffles baffleFaces '(baffle1Wall_0 baffle1Wall_1)' -overwrite > log.createBaffles 2>&1
# Create second baffle
createBaffles baffleFaces2 '(baffle2Wall_0 baffle2Wall_1)' -overwrite > log.createBaffles 2>&1

# Reset proper values at the baffles
runApplication changeDictionary

runApplication $application
