#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication blockMesh


# Creating patches 'out of nothing' so willl get undefined value which
# might cause floating point error
unset FOAM_SIGFPE
unset FOAM_SETNAN

# Add cyclic baffles for fan
runApplication setSet -batch selectCyclics.setSet
#runApplication createBaffles cyclicFaces '(fan_half0 fan_half1)' -overwrite
createBaffles cyclicFaces '(fan_half0 fan_half1)' -overwrite > log.createBaffles 2>&1

# Add wall baffles
rm log.setSet
runApplication setSet -batch selectBaffles.setSet
rm log.createBaffles
#runApplication createBaffles baffleFaces '(baffles baffles)' -overwrite
createBaffles baffleFaces '(baffles baffles)' -overwrite > log.createBaffles 2>&1

runApplication $application
