#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake

wmake SRFSimpleFoam
wmake MRFSimpleFoam
wmake windSimpleFoam
wmake porousSimpleFoam

# ----------------------------------------------------------------- end-of-file
