#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cases=" \
shockTube \
wedge15Ma5 \
obliqueShock \
forwardStep \
LadenburgJet60psi \
biconic25-55Run35 \
"

for caseName in $cases
do
(
    cd $caseName || exit

    if [ "$caseName" = shockTube ]
    then
        rm -rf 0
        cp -r 0.org 0
    fi

    foamCleanTutorials && cleanSamples

    if [ "$caseName" = "biconic25-55Run35" ]
    then
        rm -rf constant/polyMesh/boundary
    fi
)
done

# ----------------------------------------------------------------- end-of-file
