#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cases=" \
shockTube \
wedge15Ma5 \
obliqueShock \
forwardStep \
LadenburgJet60psi \
biconic25-55Run35 \
"

moveTimeMeshToConstant()
{
   DT=`foamInfoExec -times | tail -1`
   if [ "$DT" != 0 ]
   then
       mv ${DT}/polyMesh/* constant/polyMesh
       rm -rf ${DT}
   fi
}


for caseName in $cases
do
(
    cd $caseName || exit

    runApplication blockMesh

    case "$caseName" in
    shockTube)
        runApplication setFields
        ;;

    biconic25-55Run35)
        runApplication datToFoam grid256.dat

        CONST="constant"
        cat $CONST/pointsHeader $CONST/points.tmp > $CONST/polyMesh/points
        runApplication collapseEdges "2e-07" 5
        moveTimeMeshToConstant

        echo "Changing patch type to wedge type in boundary file"
        mv $CONST/polyMesh/boundary $CONST/polyMesh/boundary.bak
        sed -f $CONST/wedgeScr $CONST/polyMesh/boundary.bak > $CONST/polyMesh/boundary
        rm $CONST/polyMesh/boundary.bak
        ;;
    esac

    runApplication `getApplication`
)
done

# ----------------------------------------------------------------- end-of-file
