/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2010-2011 OpenCFD Ltd.
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

\mainpage OpenFOAM&reg;: open source CFD

\section about About OpenFOAM

    OpenFOAM is a free, open source CFD software package produced by
    a commercial company,
    <a href="http://www.openfoam.com/about">OpenCFD Ltd</a>.
    It has a large user base across most areas of engineering and
    science, from both commercial and academic organisations.
    OpenFOAM has an extensive range of features to solve anything from
    complex fluid flows involving chemical reactions, turbulence and
    heat transfer, to solid dynamics and electromagnetics.
    <a href="http://www.openfoam.com/features">More ...</a>

\section users Our commitment to the users

    OpenFOAM comes with full commercial support from OpenCFD, including
    <a href="http://www.openfoam.com/support/software.php">
    software support</a>,
    <a href="http://www.openfoam.com/support/development.php">
    contracted developments</a>
    and a programme of
    <a href="http://www.openfoam.com/training/">
    training courses</a>.
    These activities fund the development, maintenance and release of
    OpenFOAM to make it an extremely viable commercial open source product.

\section opensource Our commitment to open source

   OpenCFD is committed to open source software, continually developing and
   maintaining OpenFOAM under the
   <a href="http://www.gnu.org/copyleft/gpl.html">
   GNU General Public Licence</a>.
   OpenFOAM will <strong>always</strong> be free of charge and open source.
   In addition, we endeavour to support other viable open source initiatives
   that will benefit science and engineering.

\*---------------------------------------------------------------------------*/
